### PR TITLE
Proper autoloading for composer, PSR-4 compliant, Cleanup

### PR DESCRIPTION
**Pull request by jmleroux**
Fix #130 for tests.

### CODE REVIEW

**Comment by jmleroux** [comment]
Hello,
Is this repo still active or should i switch to some fork ?

**Comment by mishal** [comment]
The author is not active anymore in this repo. 

There are several branches which try to fix the autoloading and namespaces collisions (including mine).

**Comment by jmleroux** [comment]
Thx for your answer, i'll switch to your repo.
You could maybe ask the ownership transfer, or some admin rights on this repo. This would be better for the future of this library.

**Comment by BathoryPeter** [comment]
Or you can try my fork: [funiq/geoPHP](https://github.com/funiq/geoPHP)
For a detailed description about improvements look at [this](https://github.com/funiq/geoPHP/commit/cae3f861ed7be41bbd8f82c3224fe8bb9792b6c7) commit.

**Comment by jmleroux** [comment]
Thanks Peter for this contribution. Very interresting.
It's just sad there is so many forks when people could have worked together... :neutral_face: 
You guys are doing a good job and it would be so much better if you could join forces.

For the record, i think i will choose mishal fork. Not because i think it is better or not, but it is more up to date with the original repo.

**Comment by mishal** [comment]
what to say.. you are absolutely right... 

I tried to contact the original author in the past (If any PRs will be merged and are worth preparing), but with no success.

**Comment by jmleroux** [comment]
I'm feeling like i should close this PR. There are already many with the same concern.
And BTW, i also feel like i should switch to a maintained fork. :disappointed:

**Pull request closed without merging**
