### PR TITLE
Misc/house keeping

### PR DESCRIPTION
**Pull request by teiling88**

### CODE REVIEW

**Comment by BathoryPeter** [comment]
Did you see the other PSR namespaced forks? For example look at my PR #125.

**Comment by teiling88** [comment]
Yes - i saw it. But i found this conversation too: https://github.com/phayes/geoPHP/pull/138 

At the moment we only (OpenCaching) need the GPX Handling.

**Comment by BathoryPeter** [comment]
I've already improved GPX handling a lot. My fork generates valid GPX files and able to read/write GPX attributes and metadata. Have a look ;)
https://github.com/funiq/geoPHP/blob/master/src/Adapter/GPX.php

**Comment by teiling88** [comment]
Thanks - i will have a look :-)

**Pull request closed without merging**
